platform :ios, '8.0'

target 'JianKeLife' do
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJExtension'
pod 'AMapLocation'
pod 'DateTools'
pod 'WechatOpenSDK'
pod 'SDCycleScrollView','~>1.75'
pod 'VerifyCode'
end
